### ISSUE TITLE
Error on hot restart. "Trying to create an already created platform view, view id: 0"

### ISSUE THREAD

**Issue by beto0607** [duyduong/flutter_native_admob#12]
Hello. I'm getting this error after a hot restart of the app.
It seems like the view is not removed when the parent is diposed.

```
E/flutter (31072): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create an already created platform view, view id: 0
E/flutter (31072):      at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:85)
E/flutter (31072):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/flutter (31072):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (31072):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/flutter (31072):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/flutter (31072):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/flutter (31072):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (31072):      at android.os.MessageQueue.next(MessageQueue.java:323)
E/flutter (31072):      at android.os.Looper.loop(Looper.java:135)
E/flutter (31072):      at android.app.ActivityThread.main(ActivityThread.java:5417)
E/flutter (31072):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (31072):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/flutter (31072):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/flutter (31072): , null)
E/flutter (31072): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (31072): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (31072): <asynchronous suspension>
E/flutter (31072): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
E/flutter (31072): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter (31072): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (31072): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (31072): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
E/flutter (31072): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (31072): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (31072): #9      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter (31072): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (31072): #11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (31072): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (31072): #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (31072): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (31072): #15     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:492:13)
E/flutter (31072): #16     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:195:19)
E/flutter (31072): #17     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:238:19)
E/flutter (31072): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (31072): #19     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:134:11)
E/flutter (31072): #20     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:373:11)
E/flutter (31072): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (31072): #22     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:410:13)
E/flutter (31072): #23     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1367:12)
E/flutter (31072): #24     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1285:20)
E/flutter (31072): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (31072): #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (31072): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (31072): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (31072): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (31072): #30     RenderProxyBoxMixin.performLayou

```

**Comment by duyduong** [comment]
This seems to be Flutter issue: https://github.com/flutter/flutter/issues/47935
